#define VISITED -1
#define EMPTY 0
#define DELIVERY_BOT 1
#define OBSTACLE 2
#define ORDER_PICKUP 3

#define BOT_START_X 0
#define BOT_START_Y 0

#define BOARD_H 8
#define BOARD_W 8

#define ORDER_COUNT 5
#define OBSTACLE_COUNT 8

#define OBSTACLE_DETECTION_RANGE 2
#define ORDER_DETECTION_RANGE 1